# Generated by Django 5.1.7 on 2025-03-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_usable_pssword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='usable_pssword',
            new_name='usable_password',
        ),
    ]
